### ISSUE TITLE
Can't build with any Zig version <=0.9.0

### ISSUE THREAD

**Issue by AkramYoussoufi** [AlpaGit/bubble-sniffer-zig#1]
Tried to run/build your zig project but it seems impossible wiht nay version I choose I always get the message

`C:\Users\Acer\AppData\Local\zig\p\12200db0894481c1998c01dd28c117e5a80078039b476c1e50cfd3e4f95da78c50eb\build.zig:195:50: error: root struct of file 'Build.Step' has no member named 'MakeOptions'
    fn make(step: *Step, make_opt: std.Build.Step.MakeOptions) anyerror!void {
                                   ~~~~~~~~~~~~~~^~~~~~~~~~~~
C:\Users\Acer\Desktop\zig\lib\std\Build\Step.zig:1:1: note: struct declared here
id: Id,
^~`

Can you please help me to fix it !
